project ‘RefreshDemo.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target ‘RefreshDemo’ do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod ‘MJRefresh’
end